from datetime import datetime
import pkgutil
import re

import heroprotocol.versions

from .model import Battleground, Gamemode, Hero

_GAMEMODE_DICT = {
    50001: Gamemode.QUICK_MATCH,
    50021: Gamemode.VERSUS_AI,
    50031: Gamemode.BRAWL,
    50041: Gamemode.PRACTICE,
    50051: Gamemode.UNRANKED_DRAFT,
    50061: Gamemode.HERO_LEAGUE,
    50071: Gamemode.TEAM_LEAGUE,
    50091: Gamemode.STORM_LEAGUE,
    50101: Gamemode.ARAM,
    -1: Gamemode.CUSTOM,
    None: Gamemode.CUSTOM,
}
_SHORT_HERO_DICT = {
    "Abat": Hero.ABATHUR,
    "Alar": Hero.ALARAK,
    "Alex": Hero.ALEXSTRASZA,
    "HANA": Hero.ANA,
    "Andu": Hero.ANDUIN,
    "Anub": Hero.ANUBARAK,
    "Arts": Hero.ARTANIS,
    "Arth": Hero.ARTHAS,
    "Auri": Hero.AURIEL,
    "Azmo": Hero.AZMODAN,
    "Fire": Hero.BLAZE,
    "Faer": Hero.BRIGHTWING,
    "Amaz": Hero.CASSIA,
    "Chen": Hero.CHEN,
    "CCho": Hero.CHO,
    "Chro": Hero.CHROMIE,
    "DVA0": Hero.DVA,
    "DEAT": Hero.DEATHWING,
    "DECK": Hero.DECKARD_CAIN,
    "Deha": Hero.DEHAKA,
    "Diab": Hero.DIABLO,
    "L90E": Hero.E_T_C,
    "Fals": Hero.FALSTAD,
    "FENX": Hero.FENIX,
    "Gall": Hero.GALL,
    "Garr": Hero.GARROSH,
    "Tink": Hero.GAZLOWE,
    "Genj": Hero.GENJI,
    "Genn": Hero.GREYMANE,
    "Guld": Hero.GULDAN,
    "Hanz": Hero.HANZO,
    "HOGG": Hero.HOGGER,
    "Illi": Hero.ILLIDAN,
    "IMPE": Hero.IMPERIUS,
    "Jain": Hero.JAINA,
    "Crus": Hero.JOHANNA,
    "Junk": Hero.JUNKRAT,
    "Kael": Hero.KAELTHAS,
    "KelT": Hero.KELTHUZAD,
    "Kerr": Hero.KERRIGAN,
    "Monk": Hero.KHARAZIM,
    "Leor": Hero.LEORIC,
    "LiLi": Hero.LI_LI,
    "Wiza": Hero.LI_MING,
    "Medi": Hero.LT_MORALES,
    "Drya": Hero.LUNARA,
    "Luci": Hero.LUCIO,
    "Maie": Hero.MAIEV,
    "MalG": Hero.MALGANIS,
    "Malf": Hero.MALFURION,
    "MALT": Hero.MALTHAEL,
    "Mdvh": Hero.MEDIVH,
    "HMEI": Hero.MEI,
    "MEPH": Hero.MEPHISTO,
    "Mura": Hero.MURADIN,
    "Murk": Hero.MURKY,
    "Witc": Hero.NAZEEBO,
    "Nova": Hero.NOVA,
    "ORPH": Hero.ORPHEA,
    "Prob": Hero.PROBIUS,
    "NXHU": Hero.QHIRA,
    "Ragn": Hero.RAGNAROS,
    "Rayn": Hero.RAYNOR,
    "Rehg": Hero.REHGAR,
    "Rexx": Hero.REXXAR,
    "Samu": Hero.SAMURO,
    "Sgth": Hero.SGT_HAMMER,
    "Barb": Hero.SONYA,
    "Stit": Hero.STITCHES,
    "STUK": Hero.STUKOV,
    "Sylv": Hero.SYLVANAS,
    "Tass": Hero.TASSADAR,
    "Butc": Hero.THE_BUTCHER,
    "Lost": Hero.THE_LOST_VIKINGS,
    "Thra": Hero.THRALL,
    "Tra0": Hero.TRACER,
    "Tych": Hero.TYCHUS,
    "Tyrl": Hero.TYRAEL,
    "Tyrd": Hero.TYRANDE,
    "Uthe": Hero.UTHER,
    "VALE": Hero.VALEERA,
    "Demo": Hero.VALLA,
    "Vari": Hero.VARIAN,
    "WHIT": Hero.WHITEMANE,
    "Necr": Hero.XUL,
    "YREL": Hero.YREL,
    "Zaga": Hero.ZAGARA,
    "Zary": Hero.ZARYA,
    "Zera": Hero.ZERATUL,
    "ZULJ": Hero.ZULJIN,
    "Rand": Hero.UNKNOWN,
}
_INTERNAL_HERO_DICT = {
    "Abathur": Hero.ABATHUR,
    "Alarak": Hero.ALARAK,
    "Alexstrasza": Hero.ALEXSTRASZA,
    "AlexstraszaDragon": Hero.ALEXSTRASZA,
    "Ana": Hero.ANA,
    "Anduin": Hero.ANDUIN,
    "Anubarak": Hero.ANUBARAK,
    "Artanis": Hero.ARTANIS,
    "Arthas": Hero.ARTHAS,
    "Auriel": Hero.AURIEL,
    "Azmodan": Hero.AZMODAN,
    "Firebat": Hero.BLAZE,
    "FaerieDragon": Hero.BRIGHTWING,
    "Butcher": Hero.THE_BUTCHER,
    "Amazon": Hero.CASSIA,
    "Chen": Hero.CHEN,
    "Cho": Hero.CHO,
    "Chromie": Hero.CHROMIE,
    "Deathwing": Hero.DEATHWING,
    "DeathwingDragonflightUnit": Hero.DEATHWING,
    "Dehaka": Hero.DEHAKA,
    "Deckard": Hero.DECKARD_CAIN,
    "Diablo": Hero.DIABLO,
    "DVa": Hero.DVA,
    "DVaPilot": Hero.DVA,
    "L90ETC": Hero.E_T_C,
    "Falstad": Hero.FALSTAD,
    "Fenix": Hero.FENIX,
    "Gall": Hero.GALL,
    "Garrosh": Hero.GARROSH,
    "Tinker": Hero.GAZLOWE,
    "Genji": Hero.GENJI,
    "Greymane": Hero.GREYMANE,
    "Guldan": Hero.GULDAN,
    "Hanzo": Hero.HANZO,
    "Hogger": Hero.HOGGER,
    "Illidan": Hero.ILLIDAN,
    "Imperius": Hero.IMPERIUS,
    "Jaina": Hero.JAINA,
    "Crusader": Hero.JOHANNA,
    "Junkrat": Hero.JUNKRAT,
    "Kaelthas": Hero.KAELTHAS,
    "KelThuzad": Hero.KELTHUZAD,
    "Kerrigan": Hero.KERRIGAN,
    "Monk": Hero.KHARAZIM,
    "Leoric": Hero.LEORIC,
    "LiLi": Hero.LI_LI,
    "Wizard": Hero.LI_MING,
    "LostVikings": Hero.THE_LOST_VIKINGS,
    "LostVikingsController": Hero.THE_LOST_VIKINGS,
    "Lucio": Hero.LUCIO,
    "Medic": Hero.LT_MORALES,
    "Dryad": Hero.LUNARA,
    "Maiev": Hero.MAIEV,
    "Malfurion": Hero.MALFURION,
    "MalGanis": Hero.MALGANIS,
    "Malthael": Hero.MALTHAEL,
    "Medivh": Hero.MEDIVH,
    "MedivhRaven": Hero.MEDIVH,
    "MeiOW": Hero.MEI,
    "Mephisto": Hero.MEPHISTO,
    "Muradin": Hero.MURADIN,
    "Murky": Hero.MURKY,
    "WitchDoctor": Hero.NAZEEBO,
    "Nova": Hero.NOVA,
    "Orphea": Hero.ORPHEA,
    "Probius": Hero.PROBIUS,
    "NexusHunter": Hero.QHIRA,
    "Ragnaros": Hero.RAGNAROS,
    "Raynor": Hero.RAYNOR,
    "Rehgar": Hero.REHGAR,
    "Rexxar": Hero.REXXAR,
    "Samuro": Hero.SAMURO,
    "SgtHammer": Hero.SGT_HAMMER,
    "Barbarian": Hero.SONYA,
    "Stitches": Hero.STITCHES,
    "Stukov": Hero.STUKOV,
    "Sylvanas": Hero.SYLVANAS,
    "Tassadar": Hero.TASSADAR,
    "Thrall": Hero.THRALL,
    "Tracer": Hero.TRACER,
    "Tychus": Hero.TYCHUS,
    "Tyrael": Hero.TYRAEL,
    "Tyrande": Hero.TYRANDE,
    "Uther": Hero.UTHER,
    "Valeera": Hero.VALEERA,
    "DemonHunter": Hero.VALLA,
    "Varian": Hero.VARIAN,
    "Whitemane": Hero.WHITEMANE,
    "Necromancer": Hero.XUL,
    "Yrel": Hero.YREL,
    "Zagara": Hero.ZAGARA,
    "Zarya": Hero.ZARYA,
    "Zeratul": Hero.ZERATUL,
    "Zuljin": Hero.ZULJIN,
    "NONE": None,
}

_LOCALIZED_HERO_DICT: dict[str, Hero] = {
    "Abathur": Hero.ABATHUR,
    "abathur": Hero.ABATHUR,
    "abatur": Hero.ABATHUR,
    "\u0430\u0431\u0430\u0442\u0443\u0440": Hero.ABATHUR,
    "\uc544\ubc14\ud22c\ub974": Hero.ABATHUR,
    "\u963f\u5df4\u745f": Hero.ABATHUR,
    "Alarak": Hero.ALARAK,
    "alarak": Hero.ALARAK,
    "\u0430\u043b\u0430\u0440\u0430\u043a": Hero.ALARAK,
    "\uc54c\ub77c\ub77c\ud06c": Hero.ALARAK,
    "\u4e9e\u62c9\u745e\u514b": Hero.ALARAK,
    "\u963f\u62c9\u7eb3\u514b": Hero.ALARAK,
    "Alexstrasza": Hero.ALEXSTRASZA,
    "alexstrasza": Hero.ALEXSTRASZA,
    "alexstraza": Hero.ALEXSTRASZA,
    "\u0430\u043b\u0435\u043a\u0441\u0442\u0440\u0430\u0437\u0430": Hero.ALEXSTRASZA,
    "\uc54c\ub809\uc2a4\ud2b8\ub77c\uc790": Hero.ALEXSTRASZA,
    "\u963f\u83b1\u514b\u4e1d\u5854\u8428": Hero.ALEXSTRASZA,
    "\u96c5\u7acb\u53f2\u5353\u838e": Hero.ALEXSTRASZA,
    "Ana": Hero.ANA,
    "ana": Hero.ANA,
    "\u0430\u043d\u0430": Hero.ANA,
    "\uc544\ub098": Hero.ANA,
    "\u5b89\u5a1c": Hero.ANA,
    "Anduin": Hero.ANDUIN,
    "\u0410\u043d\u0434\u0443\u0438\u043d": Hero.ANDUIN,
    "\uc548\ub450\uc778": Hero.ANDUIN,
    "\u5b89\u5ea6\u56e0": Hero.ANDUIN,
    "\u5b89\u675c\u56e0": Hero.ANDUIN,
    "Anub'arak": Hero.ANUBARAK,
    "anub'arak": Hero.ANUBARAK,
    "Anub\u2019arak": Hero.ANUBARAK,
    "anub\u2019arak": Hero.ANUBARAK,
    "\u0430\u043d\u0443\u0431'\u0430\u0440\u0430\u043a": Hero.ANUBARAK,
    "\uc544\ub215\uc544\ub77d": Hero.ANUBARAK,
    "\u963f\u52aa\u5df4\u62c9\u514b": Hero.ANUBARAK,
    "Artanis": Hero.ARTANIS,
    "artanis": Hero.ARTANIS,
    "\u0430\u0440\u0442\u0430\u043d\u0438\u0441": Hero.ARTANIS,
    "\uc544\ub974\ud0c0\ub2c8\uc2a4": Hero.ARTANIS,
    "\u4e9e\u5766\u5c3c\u65af": Hero.ARTANIS,
    "\u963f\u5854\u5c3c\u65af": Hero.ARTANIS,
    "Arthas": Hero.ARTHAS,
    "arthas": Hero.ARTHAS,
    "\u0430\u0440\u0442\u0430\u0441": Hero.ARTHAS,
    "\uc544\uc11c\uc2a4": Hero.ARTHAS,
    "\u963f\u5c14\u8428\u65af": Hero.ARTHAS,
    "\u963f\u85a9\u65af": Hero.ARTHAS,
    "Auriel": Hero.AURIEL,
    "auriel": Hero.AURIEL,
    "\u0410\u0443\u0440\u0438\u044d\u043b\u044c": Hero.AURIEL,
    "\u0430\u0443\u0440\u0438\u044d\u043b\u044c": Hero.AURIEL,
    "\uc544\uc6b0\ub9ac\uc5d8": Hero.AURIEL,
    "\u5965\u8389\u5c14": Hero.AURIEL,
    "\u5967\u8389\u723e": Hero.AURIEL,
    "Azmodan": Hero.AZMODAN,
    "Asmodan": Hero.AZMODAN,
    "asmodan": Hero.AZMODAN,
    "azmadan": Hero.AZMODAN,
    "azmodan": Hero.AZMODAN,
    "azmod\u00e1n": Hero.AZMODAN,
    "\u0430\u0437\u043c\u043e\u0434\u0430\u043d": Hero.AZMODAN,
    "\uc544\uc988\ubaa8\ub2e8": Hero.AZMODAN,
    "\u963f\u5179\u83ab\u4e39": Hero.AZMODAN,
    "\u963f\u8332\u83ab\u4e39": Hero.AZMODAN,
    "Blaze": Hero.BLAZE,
    "blaze": Hero.BLAZE,
    "firebat": Hero.BLAZE,
    "kramer": Hero.BLAZE,
    "po\u017carsky": Hero.BLAZE,
    "vulcano": Hero.BLAZE,
    "\u0431\u043b\u044d\u0439\u0437": Hero.BLAZE,
    "\ube14\ub808\uc774\uc988": Hero.BLAZE,
    "\u5e03\u96f7\u6cfd": Hero.BLAZE,
    "\u7206\u7130": Hero.BLAZE,
    "Brightwing": Hero.BRIGHTWING,
    "Alachiara": Hero.BRIGHTWING,
    "alachiara": Hero.BRIGHTWING,
    "alafeliz": Hero.BRIGHTWING,
    "alasol": Hero.BRIGHTWING,
    "asaluz": Hero.BRIGHTWING,
    "brightwing": Hero.BRIGHTWING,
    "Funkelchen": Hero.BRIGHTWING,
    "funkelchen": Hero.BRIGHTWING,
    "jasnoskrzyd\u0142a": Hero.BRIGHTWING,
    "Luisaile": Hero.BRIGHTWING,
    "luisaile": Hero.BRIGHTWING,
    "\u0441\u0432\u0435\u0442\u0438\u043a": Hero.BRIGHTWING,
    "\ube5b\ub098\ub798": Hero.BRIGHTWING,
    "\u4eae\u7ffc": Hero.BRIGHTWING,
    "\u5149\u660e\u4e4b\u7ffc": Hero.BRIGHTWING,
    "Cassia": Hero.CASSIA,
    "cassia": Hero.CASSIA,
    "c\u00e1ssia": Hero.CASSIA,
    "kasja": Hero.CASSIA,
    "\u043a\u0430\u0441\u0441\u0438\u044f": Hero.CASSIA,
    "\uce74\uc2dc\uc544": Hero.CASSIA,
    "\u5361\u897f\u5a05": Hero.CASSIA,
    "\u5361\u897f\u96c5": Hero.CASSIA,
    "Chen": Hero.CHEN,
    "chen": Hero.CHEN,
    "czen": Hero.CHEN,
    "\u0447\u044d\u043d\u044c": Hero.CHEN,
    "\uccb8": Hero.CHEN,
    "\u8001\u9673": Hero.CHEN,
    "\u9648": Hero.CHEN,
    "Cho": Hero.CHO,
    "cha": Hero.CHO,
    "che": Hero.CHO,
    "cho": Hero.CHO,
    "czo": Hero.CHO,
    "\u0447\u043e": Hero.CHO,
    "\ucd08": Hero.CHO,
    "\u4e18": Hero.CHO,
    "\u53e4": Hero.CHO,
    "Chromie": Hero.CHROMIE,
    "chromie": Hero.CHROMIE,
    "chronia": Hero.CHROMIE,
    "Cromi": Hero.CHROMIE,
    "cromi": Hero.CHROMIE,
    "cromie": Hero.CHROMIE,
    "Crona": Hero.CHROMIE,
    "crona": Hero.CHROMIE,
    "\u0445\u0440\u043e\u043c\u0438": Hero.CHROMIE,
    "\ud06c\ub85c\ubbf8": Hero.CHROMIE,
    "\u514b\u7f57\u7c73": Hero.CHROMIE,
    "\u514b\u7f85\u7c73": Hero.CHROMIE,
    "D.Va": Hero.DVA,
    "d.va": Hero.DVA,
    "Deathwing": Hero.DEATHWING,
    "Aile de mort": Hero.DEATHWING,
    "Alamorte": Hero.DEATHWING,
    "Alamuerte": Hero.DEATHWING,
    "Asa da Morte": Hero.DEATHWING,
    "\u015amiercioskrzyd\u0142y": Hero.DEATHWING,
    "Todesschwinge": Hero.DEATHWING,
    "\u0421\u043c\u0435\u0440\u0442\u043e\u043a\u0440\u044b\u043b": Hero.DEATHWING,
    "\ub370\uc2a4\uc719": Hero.DEATHWING,
    "\u6b7b\u4ea1\u4e4b\u7ffc": Hero.DEATHWING,
    "Deckard": Hero.DECKARD_CAIN,
    "deckard": Hero.DECKARD_CAIN,
    "\u0434\u0435\u043a\u0430\u0440\u0434": Hero.DECKARD_CAIN,
    "\ub370\ucee4\ub4dc": Hero.DECKARD_CAIN,
    "\u51f1\u6069": Hero.DECKARD_CAIN,
    "\u8fea\u5361\u5fb7": Hero.DECKARD_CAIN,
    "Dehaka": Hero.DEHAKA,
    "dehaka": Hero.DEHAKA,
    "\u0434\u0435\u0445\u0430\u043a\u0430": Hero.DEHAKA,
    "\ub370\ud558\uce74": Hero.DEHAKA,
    "\u5fb7\u54c8\u5361": Hero.DEHAKA,
    "Diablo": Hero.DIABLO,
    "diablo": Hero.DIABLO,
    "\u0434\u0438\u0430\u0431\u043b\u043e": Hero.DIABLO,
    "\ub178\uc804\uc218": Hero.DIABLO,
    "\ub514\uc544\ube14\ub85c": Hero.DIABLO,
    "\u8fea\u4e9a\u6ce2\u7f57": Hero.DIABLO,
    "\u8fea\u4e9e\u5e03\u7f85": Hero.DIABLO,
    "E.T.C.": Hero.E_T_C,
    "c.t.e.": Hero.E_T_C,
    "e.t.c.": Hero.E_T_C,
    "etc": Hero.E_T_C,
    "\uc815\uc608 \ud0c0\uc6b0\ub80c \uc871\uc7a5": Hero.E_T_C,
    "\u7cbe\u82f1\u725b\u5934\u4eba\u914b\u957f": Hero.E_T_C,
    "\u7cbe\u82f1\u725b\u982d\u5927\u4f6c": Hero.E_T_C,
    "Falstad": Hero.FALSTAD,
    "falstad": Hero.FALSTAD,
    "\u0444\u0430\u043b\u0441\u0442\u0430\u0434": Hero.FALSTAD,
    "\ud3f4\uc2a4\ud0c0\ud2b8": Hero.FALSTAD,
    "\u5f17\u65af\u5854\u5fb7": Hero.FALSTAD,
    "Fenix": Hero.FENIX,
    "F\u00e9nix": Hero.FENIX,
    "fenix": Hero.FENIX,
    "f\u00e9nix": Hero.FENIX,
    "\u0444\u0435\u043d\u0438\u043a\u0441": Hero.FENIX,
    "\ud53c\ub2c9\uc2a4": Hero.FENIX,
    "\u83f2\u5c3c\u514b\u65af": Hero.FENIX,
    "Gall": Hero.GALL,
    "gal": Hero.GALL,
    "gall": Hero.GALL,
    "\u0433\u0430\u043b\u043b": Hero.GALL,
    "\uac08": Hero.GALL,
    "\u52a0\u5229": Hero.GALL,
    "\u52a0\u5c14": Hero.GALL,
    "Garrosh": Hero.GARROSH,
    "garosz": Hero.GARROSH,
    "garrosh": Hero.GARROSH,
    "\u0413\u0430\u0440\u0440\u043e\u0448": Hero.GARROSH,
    "\u0433\u0430\u0440\u0440\u043e\u0448": Hero.GARROSH,
    "\uac00\ub85c\uc26c": Hero.GARROSH,
    "\u52a0\u5c14\u9c81\u4ec0": Hero.GARROSH,
    "\u5361\u723e\u6d1b\u65af": Hero.GARROSH,
    "Gazlowe": Hero.GAZLOWE,
    "gasganete": Hero.GAZLOWE,
    "gazleu": Hero.GAZLOWE,
    "gazlowe": Hero.GAZLOWE,
    "gazol": Hero.GAZLOWE,
    "sparachiodi": Hero.GAZLOWE,
    "\u0433\u0430\u0437\u043b\u043e\u0443": Hero.GAZLOWE,
    "\uac00\uc988\ub85c": Hero.GAZLOWE,
    "\u52a0\u5179\u9c81\u7ef4": Hero.GAZLOWE,
    "\u52a0\u8332\u9b6f\u7dad": Hero.GAZLOWE,
    "Genji": Hero.GENJI,
    "genji": Hero.GENJI,
    "\u0433\u044d\u043d\u0434\u0437\u0438": Hero.GENJI,
    "\uac90\uc9c0": Hero.GENJI,
    "\u6e90\u6c0f": Hero.GENJI,
    "Greymane": Hero.GREYMANE,
    "Cringris": Hero.GREYMANE,
    "cringris": Hero.GREYMANE,
    "cringr\u00eds": Hero.GREYMANE,
    "graum\u00e4hne": Hero.GREYMANE,
    "greymane": Hero.GREYMANE,
    "griset\u00eate": Hero.GREYMANE,
    "mantogrigio": Hero.GREYMANE,
    "Szarogrzywy": Hero.GREYMANE,
    "szarogrzywy": Hero.GREYMANE,
    "\u0441\u0435\u0434\u043e\u0433\u0440\u0438\u0432": Hero.GREYMANE,
    "\uadf8\ub808\uc774\uba54\uc778": Hero.GREYMANE,
    "\u683c\u96f7\u8fc8\u6069": Hero.GREYMANE,
    "\u845b\u96f7\u9081\u6069": Hero.GREYMANE,
    "Gul'dan": Hero.GULDAN,
    "gul'dan": Hero.GULDAN,
    "gul\u2019dan": Hero.GULDAN,
    "\u0413\u0443\u043b'\u0434\u0430\u043d": Hero.GULDAN,
    "\u0433\u0443\u043b'\u0434\u0430\u043d": Hero.GULDAN,
    "\uad74\ub2e8": Hero.GULDAN,
    "\u53e4\u5c14\u4e39": Hero.GULDAN,
    "\u53e4\u723e\u4e39": Hero.GULDAN,
    "Hanzo": Hero.HANZO,
    "hanzo": Hero.HANZO,
    "\u0445\u0430\u043d\u0434\u0437\u043e": Hero.HANZO,
    "\ud55c\uc870": Hero.HANZO,
    "\u534a\u85cf": Hero.HANZO,
    "Hogger": Hero.HOGGER,
    "Boccalarga": Hero.HOGGER,
    "Lardeur": Hero.HOGGER,
    "Wy\u017cer": Hero.HOGGER,
    "\u0414\u0440\u043e\u0431\u0438\u0442\u0435\u043b\u044c": Hero.HOGGER,
    "\ub4e4\ucc3d\ucf54": Hero.HOGGER,
    "\u970d\u683c": Hero.HOGGER,
    "Illidan": Hero.ILLIDAN,
    "illidan": Hero.ILLIDAN,
    "\u0438\u043b\u043b\u0438\u0434\u0430\u043d": Hero.ILLIDAN,
    "\uc77c\ub9ac\ub2e8": Hero.ILLIDAN,
    "\u4f0a\u5229\u4e39": Hero.ILLIDAN,
    "Imperius": Hero.IMPERIUS,
    "Imp\u00e9rius": Hero.IMPERIUS,
    "\u0418\u043c\u043f\u0435\u0440\u0438\u0439": Hero.IMPERIUS,
    "\uc784\ud398\ub9ac\uc6b0\uc2a4": Hero.IMPERIUS,
    "\u82f1\u666e\u745e\u65af": Hero.IMPERIUS,
    "Jaina": Hero.JAINA,
    "jaina": Hero.JAINA,
    "\u0434\u0436\u0430\u0439\u043d\u0430": Hero.JAINA,
    "\uc81c\uc774\ub098": Hero.JAINA,
    "\u5409\u5b89\u5a1c": Hero.JAINA,
    "\u73cd\u5a1c": Hero.JAINA,
    "Johanna": Hero.JOHANNA,
    "johanna": Hero.JOHANNA,
    "\u0434\u0436\u043e\u0430\u043d\u043d\u0430": Hero.JOHANNA,
    "\uc694\ud55c\ub098": Hero.JOHANNA,
    "\u4e54\u6c49\u5a1c": Hero.JOHANNA,
    "\u55ac\u5b89\u5a1c": Hero.JOHANNA,
    "Junkrat": Hero.JUNKRAT,
    "chacal": Hero.JUNKRAT,
    "junkrat": Hero.JUNKRAT,
    "Z\u0142omiarz": Hero.JUNKRAT,
    "z\u0142omiarz": Hero.JUNKRAT,
    "\u043a\u0440\u044b\u0441\u0430\u0432\u0447\u0438\u043a": Hero.JUNKRAT,
    "\uc815\ud06c\ub7ab": Hero.JUNKRAT,
    "\u70b8\u5f48\u9f20": Hero.JUNKRAT,
    "\u72c2\u9f20": Hero.JUNKRAT,
    "Kael'thas": Hero.KAELTHAS,
    "kael'thas": Hero.KAELTHAS,
    "Kael\u2019thas": Hero.KAELTHAS,
    "kael\u2019thas": Hero.KAELTHAS,
    "\u041a\u0435\u043b\u044c'\u0442\u0430\u0441": Hero.KAELTHAS,
    "\u043a\u0435\u043b\u044c'\u0442\u0430\u0441": Hero.KAELTHAS,
    "\uce98\ud0c0\uc2a4": Hero.KAELTHAS,
    "\u51ef\u5c14\u8428\u65af": Hero.KAELTHAS,
    "\u51f1\u723e\u85a9\u65af": Hero.KAELTHAS,
    "Kel'Thuzad": Hero.KELTHUZAD,
    "kel'thuzad": Hero.KELTHUZAD,
    "kel\u2019thuzad": Hero.KELTHUZAD,
    "\u043a\u0435\u043b'\u0442\u0443\u0437\u0430\u0434": Hero.KELTHUZAD,
    "\ucf08\ud22c\uc790\ub4dc": Hero.KELTHUZAD,
    "\u514b\u5c14\u82cf\u52a0\u5fb7": Hero.KELTHUZAD,
    "\u79d1\u723e\u8607\u52a0\u5fb7": Hero.KELTHUZAD,
    "Kerrigan": Hero.KERRIGAN,
    "kerrigan": Hero.KERRIGAN,
    "\u043a\u0435\u0440\u0440\u0438\u0433\u0430\u043d": Hero.KERRIGAN,
    "\ucf00\ub9ac\uac74": Hero.KERRIGAN,
    "\u51ef\u745e\u7518": Hero.KERRIGAN,
    "\u51f1\u8389\u6839": Hero.KERRIGAN,
    "Kharazim": Hero.KHARAZIM,
    "kharazim": Hero.KHARAZIM,
    "\u043a\u0430\u0440\u0430\u0437\u0438\u043c": Hero.KHARAZIM,
    "\uce74\ub77c\uc9d0": Hero.KHARAZIM,
    "\u514b\u62c9\u8f9b": Hero.KHARAZIM,
    "\u5361\u62c9\u8f9b\u59c6": Hero.KHARAZIM,
    "Leoric": Hero.LEORIC,
    "L\u00e9oric": Hero.LEORIC,
    "leoric": Hero.LEORIC,
    "l\u00e9oric": Hero.LEORIC,
    "Leoryk": Hero.LEORIC,
    "leoryk": Hero.LEORIC,
    "\u043b\u0435\u043e\u0440\u0438\u043a": Hero.LEORIC,
    "\ub808\uc624\ub9ad": Hero.LEORIC,
    "\u674e\u5965\u745e\u514b": Hero.LEORIC,
    "\u674e\u5967\u745e\u514b": Hero.LEORIC,
    "Li Li": Hero.LI_LI,
    "li li": Hero.LI_LI,
    "\u041b\u0438 \u041b\u0438": Hero.LI_LI,
    "\u043b\u0438 \u043b\u0438": Hero.LI_LI,
    "\ub9ac \ub9ac": Hero.LI_LI,
    "\u4e3d\u4e3d": Hero.LI_LI,
    "\u8389\u8389": Hero.LI_LI,
    "Li-Ming": Hero.LI_MING,
    "li-ming": Hero.LI_MING,
    "\u043b\u0438-\u043c\u0438\u043d": Hero.LI_MING,
    "\ub9ac\ubc0d": Hero.LI_MING,
    "\u674e\u654f": Hero.LI_MING,
    "Lt. Morales": Hero.LT_MORALES,
    "lt morales": Hero.LT_MORALES,
    "lt. morales": Hero.LT_MORALES,
    "por. morales": Hero.LT_MORALES,
    "ten. morales": Hero.LT_MORALES,
    "teniente morales": Hero.LT_MORALES,
    "tte. morales": Hero.LT_MORALES,
    "\u043b\u0435\u0439\u0442\u0435\u043d\u0430\u043d\u0442 \u043c\u043e\u0440\u0430\u043b\u0435\u0441": Hero.LT_MORALES,
    "\ubaa8\ub784\ub808\uc2a4 \uc911\uc704": Hero.LT_MORALES,
    "\u83ab\u62c9\u8389\u65af\u4e2d\u5c09": Hero.LT_MORALES,
    "\u83ab\u62c9\u840a\u65af\u4e2d\u5c09": Hero.LT_MORALES,
    "L\u00facio": Hero.LUCIO,
    "lucio": Hero.LUCIO,
    "l\u00facio": Hero.LUCIO,
    "\u041b\u0443\u0441\u0438\u043e": Hero.LUCIO,
    "\u043b\u0443\u0441\u0438\u043e": Hero.LUCIO,
    "\ub8e8\uc2dc\uc6b0": Hero.LUCIO,
    "\u5362\u897f\u5965": Hero.LUCIO,
    "\u8def\u897f\u6b50": Hero.LUCIO,
    "Lunara": Hero.LUNARA,
    "ayhapa": Hero.LUNARA,
    "lunara": Hero.LUNARA,
    "\u041b\u0443\u043d\u0430\u0440\u0430": Hero.LUNARA,
    "\u043b\u0443\u043d\u0430\u0440\u0430": Hero.LUNARA,
    "\ub8e8\ub098\ub77c": Hero.LUNARA,
    "\u9732\u5a1c\u62c9": Hero.LUNARA,
    "Maiev": Hero.MAIEV,
    "maiev": Hero.MAIEV,
    "\u043c\u0430\u0439\u0435\u0432": Hero.MAIEV,
    "\ub9c8\uc774\uc5d0\ube0c": Hero.MAIEV,
    "\u739b\u7ef4": Hero.MAIEV,
    "\u746a\u7ffc\u592b": Hero.MAIEV,
    "Mal'Ganis": Hero.MALGANIS,
    "Mal\u2019Ganis": Hero.MALGANIS,
    "Mal`Ganis": Hero.MALGANIS,
    "\u041c\u0430\u043b'\u0413\u0430\u043d\u0438\u0441": Hero.MALGANIS,
    "\ub9d0\uac00\ub2c8\uc2a4": Hero.MALGANIS,
    "\u739b\u5c14\u52a0\u5c3c\u65af": Hero.MALGANIS,
    "\u746a\u723e\u52a0\u5c3c\u65af": Hero.MALGANIS,
    "Malfurion": Hero.MALFURION,
    "malfurion": Hero.MALFURION,
    "\u043c\u0430\u043b\u0444\u0443\u0440\u0438\u043e\u043d": Hero.MALFURION,
    "\ub9d0\ud4e8\ub9ac\uc628": Hero.MALFURION,
    "\u739b\u6cd5\u91cc\u5965": Hero.MALFURION,
    "\u746a\u6cd5\u91cc\u6069": Hero.MALFURION,
    "Malthael": Hero.MALTHAEL,
    "maltael": Hero.MALTHAEL,
    "malthael": Hero.MALTHAEL,
    "maltha\u00ebl": Hero.MALTHAEL,
    "\u043c\u0430\u043b\u0442\u0430\u044d\u043b\u044c": Hero.MALTHAEL,
    "\ub9d0\ud2f0\uc5d8": Hero.MALTHAEL,
    "\u746a\u745f\u723e": Hero.MALTHAEL,
    "\u9a6c\u8428\u4f0a\u5c14": Hero.MALTHAEL,
    "Medivh": Hero.MEDIVH,
    "medivh": Hero.MEDIVH,
    "\u043c\u0435\u0434\u0438\u0432": Hero.MEDIVH,
    "\uba54\ub514\ube0c": Hero.MEDIVH,
    "\u9ea5\u8fea\u6587": Hero.MEDIVH,
    "\u9ea6\u8fea\u6587": Hero.MEDIVH,
    "Mei": Hero.MEI,
    "\u041c\u044d\u0439": Hero.MEI,
    "\uba54\uc774": Hero.MEI,
    "\u5c0f\u7f8e": Hero.MEI,
    "\u7f8e": Hero.MEI,
    "Mephisto": Hero.MEPHISTO,
    "Mefisto": Hero.MEPHISTO,
    "M\u00e9phisto": Hero.MEPHISTO,
    "\u041c\u0435\u0444\u0438\u0441\u0442\u043e": Hero.MEPHISTO,
    "\uba54\ud53c\uc2a4\ud1a0": Hero.MEPHISTO,
    "\u58a8\u83f2\u65af\u6258": Hero.MEPHISTO,
    "Muradin": Hero.MURADIN,
    "muradin": Hero.MURADIN,
    "\u041c\u0443\u0440\u0430\u0434\u0438\u043d": Hero.MURADIN,
    "\u043c\u0443\u0440\u0430\u0434\u0438\u043d": Hero.MURADIN,
    "\ubb34\ub77c\ub518": Hero.MURADIN,
    "\u7a46\u62c9\u4e01": Hero.MURADIN,
    "Murky": Hero.MURKY,
    "bourbie": Hero.MURKY,
    "fosky": Hero.MURKY,
    "m\u0119cik": Hero.MURKY,
    "murky": Hero.MURKY,
    "murquinho": Hero.MURKY,
    "\u043c\u0443\u0440\u0447\u0430\u043b\u044c": Hero.MURKY,
    "\uba38\ud0a4": Hero.MURKY,
    "\u5954\u6ce2\u5c14\u9738": Hero.MURKY,
    "\u83ab\u5947": Hero.MURKY,
    "\u9c7c\u4eba": Hero.MURKY,
    "Nazeebo": Hero.NAZEEBO,
    "f\u00e9ticheur": Hero.NAZEEBO,
    "hexendoktor": Hero.NAZEEBO,
    "medico brujo": Hero.NAZEEBO,
    "Nasibo": Hero.NAZEEBO,
    "nasibo": Hero.NAZEEBO,
    "nazebo": Hero.NAZEEBO,
    "nazeebo": Hero.NAZEEBO,
    "nazibo": Hero.NAZEEBO,
    "sciamano": Hero.NAZEEBO,
    "szaman": Hero.NAZEEBO,
    "witch doctor": Hero.NAZEEBO,
    "\u043d\u0430\u0437\u0438\u0431\u043e": Hero.NAZEEBO,
    "\ub098\uc9c0\ubcf4": Hero.NAZEEBO,
    "\u7d0d\u5947\u73ed": Hero.NAZEEBO,
    "\u7eb3\u5179\u6ce2": Hero.NAZEEBO,
    "Nova": Hero.NOVA,
    "nova": Hero.NOVA,
    "\u043d\u043e\u0432\u0430": Hero.NOVA,
    "\ub178\ubc14": Hero.NOVA,
    "\u8afe\u5a03": Hero.NOVA,
    "\u8bfa\u5a03": Hero.NOVA,
    "Orphea": Hero.ORPHEA,
    "Orfea": Hero.ORPHEA,
    "Orf\u00e9a": Hero.ORPHEA,
    "Orph\u00e9a": Hero.ORPHEA,
    "orphea": Hero.ORPHEA,
    "\u041e\u0440\u0444\u0435\u044f": Hero.ORPHEA,
    "\uc624\ub974\ud53c\uc544": Hero.ORPHEA,
    "\u5965\u83f2\u5a05": Hero.ORPHEA,
    "\u6b50\u83f2\u4e9e": Hero.ORPHEA,
    "Probius": Hero.PROBIUS,
    "edn-os": Hero.PROBIUS,
    "probius": Hero.PROBIUS,
    "probiusz": Hero.PROBIUS,
    "sondius": Hero.PROBIUS,
    "\u043f\u0440\u043e\u0431\u0438\u0443\u0441": Hero.PROBIUS,
    "\ud504\ub85c\ube44\uc6b0\uc2a4": Hero.PROBIUS,
    "\u666e\u7f57\u6bd4\u65af": Hero.PROBIUS,
    "\u666e\u7f85\u6bd4\u65af": Hero.PROBIUS,
    "Qhira": Hero.QHIRA,
    "\u041a\u0430\u0445\u0438\u0440\u0430": Hero.QHIRA,
    "\ud0a4\ud788\ub77c": Hero.QHIRA,
    "\u5947\u83c8": Hero.QHIRA,
    "\u742a\u62c9": Hero.QHIRA,
    "Ragnaros": Hero.RAGNAROS,
    "ragnaros": Hero.RAGNAROS,
    "\u0440\u0430\u0433\u043d\u0430\u0440\u043e\u0441": Hero.RAGNAROS,
    "\ub77c\uadf8\ub098\ub85c\uc2a4": Hero.RAGNAROS,
    "\u62c9\u683c\u7d0d\u7f85\u65af": Hero.RAGNAROS,
    "\u62c9\u683c\u7eb3\u7f57\u65af": Hero.RAGNAROS,
    "Raynor": Hero.RAYNOR,
    "raynor": Hero.RAYNOR,
    "\u0440\u0435\u0439\u043d\u043e\u0440": Hero.RAYNOR,
    "\ub808\uc774\ub108": Hero.RAYNOR,
    "\u96f7\u8afe": Hero.RAYNOR,
    "\u96f7\u8bfa": Hero.RAYNOR,
    "Rehgar": Hero.REHGAR,
    "rehgar": Hero.REHGAR,
    "\u0440\u0435\u0433\u0430\u0440": Hero.REHGAR,
    "\ub808\uac00\ub974": Hero.REHGAR,
    "\u96f7\u52a0": Hero.REHGAR,
    "\u96f7\u52a0\u5c14": Hero.REHGAR,
    "Rexxar": Hero.REXXAR,
    "rexxar": Hero.REXXAR,
    "\u0440\u0435\u043a\u0441\u0430\u0440": Hero.REXXAR,
    "\ub809\uc0ac\ub974": Hero.REXXAR,
    "\u96f7\u514b\u8428": Hero.REXXAR,
    "\u96f7\u514b\u85a9": Hero.REXXAR,
    "Samuro": Hero.SAMURO,
    "samura": Hero.SAMURO,
    "samuro": Hero.SAMURO,
    "\u0441\u0430\u043c\u0443\u0440\u043e": Hero.SAMURO,
    "\uc0ac\ubb34\ub85c": Hero.SAMURO,
    "\u8428\u7a46\u7f57": Hero.SAMURO,
    "\u85a9\u59c6\u7f85": Hero.SAMURO,
    "Sgt. Hammer": Hero.SGT_HAMMER,
    "sargento maza": Hero.SGT_HAMMER,
    "sergeant hammer": Hero.SGT_HAMMER,
    "sergente hammer": Hero.SGT_HAMMER,
    "sgt marteau": Hero.SGT_HAMMER,
    "sgt. hammer": Hero.SGT_HAMMER,
    "sgt. marreta": Hero.SGT_HAMMER,
    "sgto. hammer": Hero.SGT_HAMMER,
    "sgto. martillo": Hero.SGT_HAMMER,
    "sier\u017c. petarda": Hero.SGT_HAMMER,
    "sier\u017cant petarda": Hero.SGT_HAMMER,
    "\u0441\u0435\u0440\u0436\u0430\u043d\u0442 \u043a\u0443\u0432\u0430\u043b\u0434\u0430": Hero.SGT_HAMMER,
    "\ud574\uba38 \uc0c1\uc0ac": Hero.SGT_HAMMER,
    "\u6994\u982d\u4e2d\u58eb": Hero.SGT_HAMMER,
    "\u91cd\u9524\u519b\u58eb": Hero.SGT_HAMMER,
    "Sonya": Hero.SONYA,
    "b\u00e1rbara": Hero.SONYA,
    "barbare": Hero.SONYA,
    "barbarian": Hero.SONYA,
    "barbarin": Hero.SONYA,
    "sonia": Hero.SONYA,
    "sonya": Hero.SONYA,
    "\u0441\u043e\u043d\u044f": Hero.SONYA,
    "\uc18c\ub0d0": Hero.SONYA,
    "\uc57c\ub9cc\uc6a9\uc0ac": Hero.SONYA,
    "\u6851\u5a05": Hero.SONYA,
    "\u6851\u96c5": Hero.SONYA,
    "\u91ce\u86ee\u4eba": Hero.SONYA,
    "\u91ce\u883b\u4eba": Hero.SONYA,
    "Stitches": Hero.STITCHES,
    "Balafr\u00e9": Hero.STITCHES,
    "balafr\u00e9": Hero.STITCHES,
    "kleiner": Hero.STITCHES,
    "puntos": Hero.STITCHES,
    "stitches": Hero.STITCHES,
    "suturino": Hero.STITCHES,
    "tritacarne": Hero.STITCHES,
    "Zszywaniec": Hero.STITCHES,
    "zszywaniec": Hero.STITCHES,
    "\u0441\u0442\u0435\u0436\u043e\u043a": Hero.STITCHES,
    "\ub204\ub354\uae30": Hero.STITCHES,
    "\u7e2b\u5408\u602a": Hero.STITCHES,
    "\u7f1d\u5408\u602a": Hero.STITCHES,
    "Stukov": Hero.STUKOV,
    "stiukow": Hero.STUKOV,
    "stukov": Hero.STUKOV,
    "\u0441\u0442\u0443\u043a\u043e\u0432": Hero.STUKOV,
    "\uc2a4\ud22c\ucf54\ud504": Hero.STUKOV,
    "\u65af\u6258\u79d1\u592b": Hero.STUKOV,
    "\u65af\u675c\u79d1\u592b": Hero.STUKOV,
    "Sylvanas": Hero.SYLVANAS,
    "sylvana": Hero.SYLVANAS,
    "sylvanas": Hero.SYLVANAS,
    "sylwana": Hero.SYLVANAS,
    "\u0441\u0438\u043b\u044c\u0432\u0430\u043d\u0430": Hero.SYLVANAS,
    "\uc2e4\ubc14\ub098\uc2a4": Hero.SYLVANAS,
    "\u5e0c\u5c14\u74e6\u5a1c\u65af": Hero.SYLVANAS,
    "\u5e0c\u74e6\u5a1c\u65af": Hero.SYLVANAS,
    "Tassadar": Hero.TASSADAR,
    "tassadar": Hero.TASSADAR,
    "\u0442\u0430\u0441\u0441\u0430\u0434\u0430\u0440": Hero.TASSADAR,
    "\ud0dc\uc0ac\ub2e4\ub974": Hero.TASSADAR,
    "\u5854\u8428\u8fbe\u5c14": Hero.TASSADAR,
    "\u5854\u85a9\u9054": Hero.TASSADAR,
    "The Butcher": Hero.THE_BUTCHER,
    "Der Schl\u00e4chter": Hero.THE_BUTCHER,
    "der schl\u00e4chter": Hero.THE_BUTCHER,
    "el carnicero": Hero.THE_BUTCHER,
    "Le Boucher": Hero.THE_BUTCHER,
    "le boucher": Hero.THE_BUTCHER,
    "macellaio": Hero.THE_BUTCHER,
    "o a\u00e7ougueiro": Hero.THE_BUTCHER,
    "rze\u017anik": Hero.THE_BUTCHER,
    "the butcher": Hero.THE_BUTCHER,
    "\u041c\u044f\u0441\u043d\u0438\u043a": Hero.THE_BUTCHER,
    "\u043c\u044f\u0441\u043d\u0438\u043a": Hero.THE_BUTCHER,
    "\ub3c4\uc0b4\uc790": Hero.THE_BUTCHER,
    "\u5c60\u592b": Hero.THE_BUTCHER,
    "The Lost Vikings": Hero.THE_LOST_VIKINGS,
    "les vikings perdus": Hero.THE_LOST_VIKINGS,
    "los vikingos perdidos": Hero.THE_LOST_VIKINGS,
    "lost vikings": Hero.THE_LOST_VIKINGS,
    "os vikings perdidos": Hero.THE_LOST_VIKINGS,
    "the lost vikings": Hero.THE_LOST_VIKINGS,
    "vichinghi sperduti": Hero.THE_LOST_VIKINGS,
    "zaginieni wikingowie": Hero.THE_LOST_VIKINGS,
    "\u043f\u043e\u0442\u0435\u0440\u044f\u0432\u0448\u0438\u0435\u0441\u044f \u0432\u0438\u043a\u0438\u043d\u0433\u0438": Hero.THE_LOST_VIKINGS,
    "\uae38 \uc783\uc740 \ubc14\uc774\ud0b9": Hero.THE_LOST_VIKINGS,
    "\u5931\u843d\u7684\u7dad\u4eac\u4eba": Hero.THE_LOST_VIKINGS,
    "\u5931\u843d\u7684\u7ef4\u4eac\u4eba": Hero.THE_LOST_VIKINGS,
    "Thrall": Hero.THRALL,
    "thrall": Hero.THRALL,
    "\u0422\u0440\u0430\u043b\u043b": Hero.THRALL,
    "\u0442\u0440\u0430\u043b\u043b": Hero.THRALL,
    "\uc2a4\ub784": Hero.THRALL,
    "\u7d22\u723e": Hero.THRALL,
    "\u8428\u5c14": Hero.THRALL,
    "Tracer": Hero.TRACER,
    "Smuga": Hero.TRACER,
    "smuga": Hero.TRACER,
    "tracer": Hero.TRACER,
    "\u0442\u0440\u0435\u0439\u0441\u0435\u0440": Hero.TRACER,
    "\ud2b8\ub808\uc774\uc11c": Hero.TRACER,
    "\u730e\u7a7a": Hero.TRACER,
    "\u9583\u5149": Hero.TRACER,
    "Tychus": Hero.TYCHUS,
    "tychus": Hero.TYCHUS,
    "\u0422\u0430\u0439\u043a\u0443\u0441": Hero.TYCHUS,
    "\u0442\u0430\u0439\u043a\u0443\u0441": Hero.TYCHUS,
    "\ud0c0\uc774\ucee4\uc2a4": Hero.TYCHUS,
    "\u6cf0\u51ef\u65af": Hero.TYCHUS,
    "\u6cf0\u79d1\u65af": Hero.TYCHUS,
    "Tyrael": Hero.TYRAEL,
    "tyrael": Hero.TYRAEL,
    "tyra\u00ebl": Hero.TYRAEL,
    "\u0442\u0438\u0440\u0430\u044d\u043b\u044c": Hero.TYRAEL,
    "\ud2f0\ub9ac\uc5d8": Hero.TYRAEL,
    "\u6cf0\u745e\u5c14": Hero.TYRAEL,
    "\u6cf0\u745e\u723e": Hero.TYRAEL,
    "Tyrande": Hero.TYRANDE,
    "tyrande": Hero.TYRANDE,
    "\u0442\u0438\u0440\u0430\u043d\u0434\u0430": Hero.TYRANDE,
    "\ud2f0\ub780\ub370": Hero.TYRANDE,
    "\u6cf0\u5170\u5fb7": Hero.TYRANDE,
    "\u6cf0\u862d\u59b2": Hero.TYRANDE,
    "Uther": Hero.UTHER,
    "uther": Hero.UTHER,
    "\u0443\u0442\u0435\u0440": Hero.UTHER,
    "\uc6b0\uc11c": Hero.UTHER,
    "\u4e4c\u745f\u5c14": Hero.UTHER,
    "\u70cf\u745f": Hero.UTHER,
    "Valeera": Hero.VALEERA,
    "valeera": Hero.VALEERA,
    "valira": Hero.VALEERA,
    "\u0432\u0430\u043b\u0438\u0440\u0430": Hero.VALEERA,
    "\ubc1c\ub9ac\ub77c": Hero.VALEERA,
    "\u74e6\u8389\u62c9": Hero.VALEERA,
    "\u74e6\u9e97\u62c9": Hero.VALEERA,
    "Valla": Hero.VALLA,
    "ca\u00e7adora de dem\u00f4nios": Hero.VALLA,
    "cacciatrice di demoni": Hero.VALLA,
    "cazadora de demonios": Hero.VALLA,
    "chasseuse de demons": Hero.VALLA,
    "d\u00e4monenj\u00e4gerin": Hero.VALLA,
    "demon hunter": Hero.VALLA,
    "\u0142owczyni demon\u00f3w": Hero.VALLA,
    "tyla": Hero.VALLA,
    "vala": Hero.VALLA,
    "valla": Hero.VALLA,
    "\u0432\u0430\u043b\u043b\u0430": Hero.VALLA,
    "\ubc1c\ub77c": Hero.VALLA,
    "\uc545\ub9c8\uc0ac\ub0e5\uafbc": Hero.VALLA,
    "\u72e9\u9b54\u7375\u4eba": Hero.VALLA,
    "\u730e\u9b54\u4eba": Hero.VALLA,
    "\u7dad\u62c9": Hero.VALLA,
    "\u7ef4\u62c9": Hero.VALLA,
    "Varian": Hero.VARIAN,
    "varian": Hero.VARIAN,
    "\u0412\u0430\u0440\u0438\u0430\u043d": Hero.VARIAN,
    "\u0432\u0430\u0440\u0438\u0430\u043d": Hero.VARIAN,
    "\ubc14\ub9ac\uc548": Hero.VARIAN,
    "\ubc14\ub9ac\uc778": Hero.VARIAN,
    "\u74e6\u91cc\u5b89": Hero.VARIAN,
    "Whitemane": Hero.WHITEMANE,
    "Bia\u0142ow\u0142osa": Hero.WHITEMANE,
    "Biancachioma": Hero.WHITEMANE,
    "Blanchet\u00eate": Hero.WHITEMANE,
    "Cristalba": Hero.WHITEMANE,
    "Melenablanca": Hero.WHITEMANE,
    "Wei\u00dfstr\u00e4hne": Hero.WHITEMANE,
    "whitemane": Hero.WHITEMANE,
    "\u0412\u0430\u0439\u0442\u043c\u0435\u0439\u043d": Hero.WHITEMANE,
    "\ud654\uc774\ud2b8\uba54\uc778": Hero.WHITEMANE,
    "\u6000\u7279\u8fc8\u6069": Hero.WHITEMANE,
    "\u61f7\u7279\u9081\u6069": Hero.WHITEMANE,
    "Xul": Hero.XUL,
    "xul": Hero.XUL,
    "\u0437\u0443\u043b": Hero.XUL,
    "\uc904": Hero.XUL,
    "\u7956\u5c14": Hero.XUL,
    "\u8607\u723e": Hero.XUL,
    "Yrel": Hero.YREL,
    "yrel": Hero.YREL,
    "\u0438\u0440\u0435\u043b\u044c": Hero.YREL,
    "\uc774\ub810": Hero.YREL,
    "\u4f0a\u745e\u5c14": Hero.YREL,
    "\u4f0a\u82ae\u723e": Hero.YREL,
    "Zagara": Hero.ZAGARA,
    "zagara": Hero.ZAGARA,
    "\u0437\u0430\u0433\u0430\u0440\u0430": Hero.ZAGARA,
    "\uc790\uac00\ub77c": Hero.ZAGARA,
    "\u624e\u52a0\u62c9": Hero.ZAGARA,
    "\u672d\u8fe6\u62c9": Hero.ZAGARA,
    "Zarya": Hero.ZARYA,
    "zaria": Hero.ZARYA,
    "zarya": Hero.ZARYA,
    "\u0437\u0430\u0440\u044f": Hero.ZARYA,
    "\uc790\ub77c\uc57c": Hero.ZARYA,
    "\uc790\ub9ac\uc57c": Hero.ZARYA,
    "\u672d\u8389\u96c5": Hero.ZARYA,
    "\u67e5\u8389\u5a05": Hero.ZARYA,
    "Zeratul": Hero.ZERATUL,
    "zeratul": Hero.ZERATUL,
    "\u0437\u0435\u0440\u0430\u0442\u0443\u043b": Hero.ZERATUL,
    "\uc81c\ub77c\ud234": Hero.ZERATUL,
    "\u6cfd\u62c9\u56fe": Hero.ZERATUL,
    "\u6fa4\u62c9\u5716": Hero.ZERATUL,
    "Zul'jin": Hero.ZULJIN,
    "zul'jin": Hero.ZULJIN,
    "zul\u2019jin": Hero.ZULJIN,
    "\u0437\u0443\u043b'\u0434\u0436\u0438\u043d": Hero.ZULJIN,
    "\uc904\uc9c4": Hero.ZULJIN,
    "\u7956\u5c14\u91d1": Hero.ZULJIN,
    "\u7956\u723e\u91d1": Hero.ZULJIN,
}
_INTERNAL_BATTLEGROUND_DICT = {
    "BattlefieldOfEternity": Battleground.BATTLEFIELD_OF_ETERNITY,
    "BlackheartsBay": Battleground.BLACKHEARTS_BAY,
    "BraxisHoldout": Battleground.BRAXIS_HOLDOUT,
    "CursedHollow": Battleground.CURSED_HOLLOW,
    "DragonShire": Battleground.DRAGON_SHIRE,
    "HauntedWoods": Battleground.GARDEN_OF_TERROR,
    "Hanamura": Battleground.HANAMURA_TEMPLE,
    "HauntedMines": Battleground.HAUNTED_MINES,
    "Shrines": Battleground.INFERNAL_SHRINES,
    "ControlPoints": Battleground.SKY_TEMPLE,
    "Crypts": Battleground.TOMB_OF_THE_SPIDER_QUEEN,
    "TowersOfDoom": Battleground.TOWERS_OF_DOOM,
    "Warhead Junction": Battleground.WARHEAD_JUNCTION,
    "Volskaya": Battleground.VOLSKAYA_FOUNDRY,
    "AlteracPass": Battleground.ALTERAC_PASS,
    "EscapeFromBraxis": Battleground.ESCAPE_FROM_BRAXIS,
    "IndustrialDistrict": Battleground.INDUSTRIAL_DISTRICT,
    "LostCavern": Battleground.LOST_CAVERN,
    "PullParty": Battleground.PULL_PARTY,
    "SilverCity": Battleground.SILVER_CITY,
    "BraxisOutpost": Battleground.BRAXIS_OUTPOST,
    "HanamuraPayloadPush": Battleground.CHECKPOINT_HANAMURA,
    "EscapeFromBraxis(Heroic)": Battleground.ESCAPE_FROM_BRAXIS_HEROIC,
}

_LOCALIZED_BATTLEGROUND_DICT = {
    "Alteracpass": Battleground.ALTERAC_PASS,
    "Alterac Pass": Battleground.ALTERAC_PASS,
    "Cañón de Alterac": Battleground.ALTERAC_PASS,
    "Paso de Alterac": Battleground.ALTERAC_PASS,
    "La passe d’Alterac": Battleground.ALTERAC_PASS,
    "Passo d'Alterac": Battleground.ALTERAC_PASS,
    "알터랙 고개": Battleground.ALTERAC_PASS,
    "Przełęcz Alterak": Battleground.ALTERAC_PASS,
    "Garganta de Alterac": Battleground.ALTERAC_PASS,
    "Альтеракский перевал": Battleground.ALTERAC_PASS,
    "奥特兰克战道": Battleground.ALTERAC_PASS,
    "奧特蘭克隘口": Battleground.ALTERAC_PASS,
    "Schlachtfeld der Ewigkeit": Battleground.BATTLEFIELD_OF_ETERNITY,
    "Battlefield of Eternity": Battleground.BATTLEFIELD_OF_ETERNITY,
    "Campos de Batalla de la Eternidad": Battleground.BATTLEFIELD_OF_ETERNITY,
    "Campo de batalla de la Eternidad": Battleground.BATTLEFIELD_OF_ETERNITY,
    "Les champs de l’éternité": Battleground.BATTLEFIELD_OF_ETERNITY,
    "Campi di Battaglia Eterni": Battleground.BATTLEFIELD_OF_ETERNITY,
    "영원의 전쟁터": Battleground.BATTLEFIELD_OF_ETERNITY,
    "Pole Bitewne Wieczności": Battleground.BATTLEFIELD_OF_ETERNITY,
    "Campo de Batalha da Eternidade": Battleground.BATTLEFIELD_OF_ETERNITY,
    "Вечная битва": Battleground.BATTLEFIELD_OF_ETERNITY,
    "永恒战场": Battleground.BATTLEFIELD_OF_ETERNITY,
    "永恆戰場": Battleground.BATTLEFIELD_OF_ETERNITY,
    "Schwarzherzbucht": Battleground.BLACKHEARTS_BAY,
    "Blackheart's Bay": Battleground.BLACKHEARTS_BAY,
    "Bahía de Almanegra": Battleground.BLACKHEARTS_BAY,
    "La baie de Cœur-Noir": Battleground.BLACKHEARTS_BAY,
    "Baia di Cuornero": Battleground.BLACKHEARTS_BAY,
    "블랙하트 항만": Battleground.BLACKHEARTS_BAY,
    "Zatoka Czarnosercego": Battleground.BLACKHEARTS_BAY,
    "Baía do Coração Negro": Battleground.BLACKHEARTS_BAY,
    "Бухта Черносерда": Battleground.BLACKHEARTS_BAY,
    "黑心湾": Battleground.BLACKHEARTS_BAY,
    "黑心灣": Battleground.BLACKHEARTS_BAY,
    "Endstation Braxis": Battleground.BRAXIS_HOLDOUT,
    "Braxis Holdout": Battleground.BRAXIS_HOLDOUT,
    "Resistencia en Braxis": Battleground.BRAXIS_HOLDOUT,
    "Le laboratoire de Braxis": Battleground.BRAXIS_HOLDOUT,
    "Distaccamento di Braxis": Battleground.BRAXIS_HOLDOUT,
    "브락시스 항전": Battleground.BRAXIS_HOLDOUT,
    "Placówka na Braxis": Battleground.BRAXIS_HOLDOUT,
    "Resistência de Braxis": Battleground.BRAXIS_HOLDOUT,
    "Бойня на Браксисе": Battleground.BRAXIS_HOLDOUT,
    "布莱克西斯禁区": Battleground.BRAXIS_HOLDOUT,
    "布萊西斯實驗所": Battleground.BRAXIS_HOLDOUT,
    "Außenposten Braxis": Battleground.BRAXIS_OUTPOST,
    "Braxis Outpost": Battleground.BRAXIS_OUTPOST,
    "Avanzada de Braxis": Battleground.BRAXIS_OUTPOST,
    "Puesto de avanzada de Braxis": Battleground.BRAXIS_OUTPOST,
    "L’avant-poste de Braxis": Battleground.BRAXIS_OUTPOST,
    "Avamposto di Braxis": Battleground.BRAXIS_OUTPOST,
    "브락시스 전초기지": Battleground.BRAXIS_OUTPOST,
    "Posterunek na Braxis": Battleground.BRAXIS_OUTPOST,
    "Posto Avançado Braxis": Battleground.BRAXIS_OUTPOST,
    "Аванпост на Браксисе": Battleground.BRAXIS_OUTPOST,
    "布莱克西斯前哨": Battleground.BRAXIS_OUTPOST,
    "布萊西斯哨站": Battleground.BRAXIS_OUTPOST,
    # TODO: Add German
    "Checkpoint: Hanamura": Battleground.CHECKPOINT_HANAMURA,
    "Punto de control: Hanamura": Battleground.CHECKPOINT_HANAMURA,
    "Point de contrôle : Hanamura": Battleground.CHECKPOINT_HANAMURA,
    "경유지: 하나무라": Battleground.CHECKPOINT_HANAMURA,
    "Punkt Kontrolny: Hanamura": Battleground.CHECKPOINT_HANAMURA,
    "Ponto de Controle: Hanamura": Battleground.CHECKPOINT_HANAMURA,
    "Контрольная точка: Ханамура": Battleground.CHECKPOINT_HANAMURA,
    "检查点：花村": Battleground.CHECKPOINT_HANAMURA,
    "激戰花村": Battleground.CHECKPOINT_HANAMURA,
    "Verfluchtes Tal": Battleground.CURSED_HOLLOW,
    "Cursed Hollow": Battleground.CURSED_HOLLOW,
    "Cuenca Maldita": Battleground.CURSED_HOLLOW,
    "Hondonada maldita": Battleground.CURSED_HOLLOW,
    "Le val maudit": Battleground.CURSED_HOLLOW,
    "Valle Maledetta": Battleground.CURSED_HOLLOW,
    "저주받은 골짜기": Battleground.CURSED_HOLLOW,
    "Przeklęta Kotlina": Battleground.CURSED_HOLLOW,
    "Clareira Maldita": Battleground.CURSED_HOLLOW,
    "Проклятая лощина": Battleground.CURSED_HOLLOW,
    "诅咒谷": Battleground.CURSED_HOLLOW,
    "詛咒谷地": Battleground.CURSED_HOLLOW,
    "Drachengärten": Battleground.DRAGON_SHIRE,
    "Dragon Shire": Battleground.DRAGON_SHIRE,
    "Condado del Dragón": Battleground.DRAGON_SHIRE,
    "Comarca del dragón": Battleground.DRAGON_SHIRE,
    "Le comté du dragon": Battleground.DRAGON_SHIRE,
    "Contea del Drago": Battleground.DRAGON_SHIRE,
    "용의 둥지": Battleground.DRAGON_SHIRE,
    "Smocze Włości": Battleground.DRAGON_SHIRE,
    "Condado do Dragão": Battleground.DRAGON_SHIRE,
    "Драконий край": Battleground.DRAGON_SHIRE,
    "巨龙镇": Battleground.DRAGON_SHIRE,
    "巨龍郡": Battleground.DRAGON_SHIRE,
    "Flucht von Braxis": Battleground.ESCAPE_FROM_BRAXIS,
    "Escape From Braxis": Battleground.ESCAPE_FROM_BRAXIS,
    "Fuga de Braxis": Battleground.ESCAPE_FROM_BRAXIS,
    "Escape de Braxis": Battleground.ESCAPE_FROM_BRAXIS,
    "La fuite de Braxis": Battleground.ESCAPE_FROM_BRAXIS,
    "Fuga da Braxis": Battleground.ESCAPE_FROM_BRAXIS,
    "브락시스 탈출": Battleground.ESCAPE_FROM_BRAXIS,
    "Ucieczka z Braxis": Battleground.ESCAPE_FROM_BRAXIS,
    "Fuga de Braxis": Battleground.ESCAPE_FROM_BRAXIS,
    "Побег с Браксиса": Battleground.ESCAPE_FROM_BRAXIS,
    "逃离布莱克西斯": Battleground.ESCAPE_FROM_BRAXIS,
    "逃離布萊西斯": Battleground.ESCAPE_FROM_BRAXIS,
    "Escape From Braxis (Heroic)": Battleground.ESCAPE_FROM_BRAXIS_HEROIC,
    "Fuga de Braxis (heroico)": Battleground.ESCAPE_FROM_BRAXIS_HEROIC,
    "Escape de Braxis (Heroico)": Battleground.ESCAPE_FROM_BRAXIS_HEROIC,
    "La fuite de Braxis (héroïque)": Battleground.ESCAPE_FROM_BRAXIS_HEROIC,
    "Fuga da Braxis (Eroica)": Battleground.ESCAPE_FROM_BRAXIS_HEROIC,
    # TODO: Add Korean
    "Heroiczna Ucieczka z Braxis": Battleground.ESCAPE_FROM_BRAXIS_HEROIC,
    "Fuga de Braxis (Heroico)": Battleground.ESCAPE_FROM_BRAXIS_HEROIC,
    "Героический побег с Браксиса": Battleground.ESCAPE_FROM_BRAXIS_HEROIC,
    "逃离布莱克西斯（英雄难度）": Battleground.ESCAPE_FROM_BRAXIS_HEROIC,
    "逃離布萊西斯（英雄模式）": Battleground.ESCAPE_FROM_BRAXIS_HEROIC,
    "Garten der Ängste": Battleground.GARDEN_OF_TERROR,
    "Garden of Terror": Battleground.GARDEN_OF_TERROR,
    "Jardín del Terror": Battleground.GARDEN_OF_TERROR,
    "Jardín del terror": Battleground.GARDEN_OF_TERROR,
    "Les jardins de terreur": Battleground.GARDEN_OF_TERROR,
    "Giardino del Terrore": Battleground.GARDEN_OF_TERROR,
    "공포의 정원": Battleground.GARDEN_OF_TERROR,
    "Ogród Grozy": Battleground.GARDEN_OF_TERROR,
    "Jardim do Terror": Battleground.GARDEN_OF_TERROR,
    "Сад ужасов": Battleground.GARDEN_OF_TERROR,
    "恐魔园": Battleground.GARDEN_OF_TERROR,
    "恐怖花園": Battleground.GARDEN_OF_TERROR,
    "Garten der Ängste (Klassisch)": Battleground.GARDEN_OF_TERROR_CLASSIC,
    "Garden of Terror Classic": Battleground.GARDEN_OF_TERROR_CLASSIC,
    "Jardín del Terror clásico": Battleground.GARDEN_OF_TERROR_CLASSIC,
    "Jardín del terror clásico": Battleground.GARDEN_OF_TERROR_CLASSIC,
    "Les jardins de terreur (classique)": Battleground.GARDEN_OF_TERROR_CLASSIC,
    "Giardino del Terrore (Classico)": Battleground.GARDEN_OF_TERROR_CLASSIC,
    "공포의 정원 클래식": Battleground.GARDEN_OF_TERROR_CLASSIC,
    "Klasyczny Ogród Grozy": Battleground.GARDEN_OF_TERROR_CLASSIC,
    "Jardim do Terror Clássico": Battleground.GARDEN_OF_TERROR_CLASSIC,
    "Сад ужасов — классика": Battleground.GARDEN_OF_TERROR_CLASSIC,
    "恐魔园经典": Battleground.GARDEN_OF_TERROR_CLASSIC,
    "恐怖花園經典版": Battleground.GARDEN_OF_TERROR_CLASSIC,
    "Tempel von Hanamura": Battleground.HANAMURA_TEMPLE,
    "Hanamura Temple": Battleground.HANAMURA_TEMPLE,
    "Templo de Hanamura": Battleground.HANAMURA_TEMPLE,
    "Le temple d’Hanamura": Battleground.HANAMURA_TEMPLE,
    "Tempio di Hanamura": Battleground.HANAMURA_TEMPLE,
    "하나무라 사원": Battleground.HANAMURA_TEMPLE,
    "Świątynia w Hanamurze": Battleground.HANAMURA_TEMPLE,
    "Храм Ханамуры": Battleground.HANAMURA_TEMPLE,
    "花村寺": Battleground.HANAMURA_TEMPLE,
    "花村神殿": Battleground.HANAMURA_TEMPLE,
    "Geisterminen": Battleground.HAUNTED_MINES,
    "Haunted Mines": Battleground.HAUNTED_MINES,
    "Minas Encantadas": Battleground.HAUNTED_MINES,
    "Minas embrujadas": Battleground.HAUNTED_MINES,
    "La mine hantée": Battleground.HAUNTED_MINES,
    "Miniere Infestate": Battleground.HAUNTED_MINES,
    "죽음의 광산": Battleground.HAUNTED_MINES,
    "Nawiedzone Kopalnie": Battleground.HAUNTED_MINES,
    "Mina Assombrada": Battleground.HAUNTED_MINES,
    "Призрачные копи": Battleground.HAUNTED_MINES,
    "鬼灵矿": Battleground.HAUNTED_MINES,
    "亡骸礦坑": Battleground.HAUNTED_MINES,
    "Industriebezirk": Battleground.INDUSTRIAL_DISTRICT,
    "Industrial District": Battleground.INDUSTRIAL_DISTRICT,
    "Distrito Industrial": Battleground.INDUSTRIAL_DISTRICT,
    "Distrito industrial": Battleground.INDUSTRIAL_DISTRICT,
    "Le district industriel": Battleground.INDUSTRIAL_DISTRICT,
    "Distretto Industriale": Battleground.INDUSTRIAL_DISTRICT,
    "공업 지구": Battleground.INDUSTRIAL_DISTRICT,
    "Dzielnica Przemysłowa": Battleground.INDUSTRIAL_DISTRICT,
    "Distrito Industrial": Battleground.INDUSTRIAL_DISTRICT,
    "Промзона": Battleground.INDUSTRIAL_DISTRICT,
    "工业园区": Battleground.INDUSTRIAL_DISTRICT,
    "機戰工業區": Battleground.INDUSTRIAL_DISTRICT,
    "Höllenschreine": Battleground.INFERNAL_SHRINES,
    "Infernal Shrines": Battleground.INFERNAL_SHRINES,
    "Santuarios Infernales": Battleground.INFERNAL_SHRINES,
    "Sagrarios Infernales": Battleground.INFERNAL_SHRINES,
    "Les sanctuaires infernaux": Battleground.INFERNAL_SHRINES,
    "Altari Infernali": Battleground.INFERNAL_SHRINES,
    "불지옥 신단": Battleground.INFERNAL_SHRINES,
    "Piekielne Kapliczki": Battleground.INFERNAL_SHRINES,
    "Santuários Infernais": Battleground.INFERNAL_SHRINES,
    "Оскверненные святилища": Battleground.INFERNAL_SHRINES,
    "炼狱圣坛": Battleground.INFERNAL_SHRINES,
    "煉獄聖壇": Battleground.INFERNAL_SHRINES,
    "Vergessene Höhle": Battleground.LOST_CAVERN,
    "Lost Cavern": Battleground.LOST_CAVERN,
    "Caverna Perdida": Battleground.LOST_CAVERN,
    "Caverna perdida": Battleground.LOST_CAVERN,
    "Le caveau perdu": Battleground.LOST_CAVERN,
    "Caverna Perduta": Battleground.LOST_CAVERN,
    "잃어버린 동굴": Battleground.LOST_CAVERN,
    "Zaginiona Pieczara": Battleground.LOST_CAVERN,
    "Затерянный грот": Battleground.LOST_CAVERN,
    "失落洞窟": Battleground.LOST_CAVERN,
    "Ich glaub, es hakt": Battleground.PULL_PARTY,
    "Pull Party": Battleground.PULL_PARTY,
    "Echar el gancho": Battleground.PULL_PARTY,
    "Fiesta de ganchos": Battleground.PULL_PARTY,
    "Accro au crochet": Battleground.PULL_PARTY,
    "Agganci pericolosi": Battleground.PULL_PARTY,
    "갈고리 파티": Battleground.PULL_PARTY,
    "Impreza przy Basenie": Battleground.PULL_PARTY,
    "Puxa-puxa": Battleground.PULL_PARTY,
    "Притягательные личности": Battleground.PULL_PARTY,
    "拉钩派对": Battleground.PULL_PARTY,
    "鉤鉤派對": Battleground.PULL_PARTY,
    "Silberne Stadt": Battleground.SILVER_CITY,
    "Silver City": Battleground.SILVER_CITY,
    "Ciudad de Plata": Battleground.SILVER_CITY,
    "Ciudad argenta": Battleground.SILVER_CITY,
    "La cité d’argent": Battleground.SILVER_CITY,
    "Città d'Argento": Battleground.SILVER_CITY,
    "은빛 도시": Battleground.SILVER_CITY,
    "Srebrne Miasto": Battleground.SILVER_CITY,
    "Cidade de Prata": Battleground.SILVER_CITY,
    "Серебряный город": Battleground.SILVER_CITY,
    "白银城": Battleground.SILVER_CITY,
    "銀光之城": Battleground.SILVER_CITY,
    "Tempel des Himmels": Battleground.SKY_TEMPLE,
    "Sky Temple": Battleground.SKY_TEMPLE,
    "Templo Celeste": Battleground.SKY_TEMPLE,
    "Templo celeste": Battleground.SKY_TEMPLE,
    "Le temple céleste": Battleground.SKY_TEMPLE,
    "Tempio Celeste": Battleground.SKY_TEMPLE,
    "하늘 사원": Battleground.SKY_TEMPLE,
    "Podniebna Świątynia": Battleground.SKY_TEMPLE,
    "Небесный храм": Battleground.SKY_TEMPLE,
    "天空殿": Battleground.SKY_TEMPLE,
    "天空神殿": Battleground.SKY_TEMPLE,
    "Grabkammer der Spinnenkönigin": Battleground.TOMB_OF_THE_SPIDER_QUEEN,
    "Tomb of the Spider Queen": Battleground.TOMB_OF_THE_SPIDER_QUEEN,
    "Tumba de la Reina Araña": Battleground.TOMB_OF_THE_SPIDER_QUEEN,
    "Tumba de la reina araña": Battleground.TOMB_OF_THE_SPIDER_QUEEN,
    "La tombe de la reine araignée": Battleground.TOMB_OF_THE_SPIDER_QUEEN,
    "Tomba della Regina Ragno": Battleground.TOMB_OF_THE_SPIDER_QUEEN,
    "거미 여왕의 무덤": Battleground.TOMB_OF_THE_SPIDER_QUEEN,
    "Grobowiec Pajęczej Królowej": Battleground.TOMB_OF_THE_SPIDER_QUEEN,
    "Tumba da Aranha Rainha": Battleground.TOMB_OF_THE_SPIDER_QUEEN,
    "Гробница Королевы Пауков": Battleground.TOMB_OF_THE_SPIDER_QUEEN,
    "蛛后墓": Battleground.TOMB_OF_THE_SPIDER_QUEEN,
    "蛛后之墓": Battleground.TOMB_OF_THE_SPIDER_QUEEN,
    "Türme des Unheils": Battleground.TOWERS_OF_DOOM,
    "Towers of Doom": Battleground.TOWERS_OF_DOOM,
    "Torres de Fatalidad": Battleground.TOWERS_OF_DOOM,
    "Torres de la perdición": Battleground.TOWERS_OF_DOOM,
    "Les tours du destin": Battleground.TOWERS_OF_DOOM,
    "Torri della Rovina": Battleground.TOWERS_OF_DOOM,
    "파멸의 탑": Battleground.TOWERS_OF_DOOM,
    "Wieże Zagłady": Battleground.TOWERS_OF_DOOM,
    "Torres da Perdição": Battleground.TOWERS_OF_DOOM,
    "Башни Рока": Battleground.TOWERS_OF_DOOM,
    "末日塔": Battleground.TOWERS_OF_DOOM,
    "厄運之塔": Battleground.TOWERS_OF_DOOM,
    "Volskaya-Fertigung": Battleground.VOLSKAYA_FOUNDRY,
    "Volskaya Foundry": Battleground.VOLSKAYA_FOUNDRY,
    "Fundición de Volskaya": Battleground.VOLSKAYA_FOUNDRY,
    "La fonderie Volskaya": Battleground.VOLSKAYA_FOUNDRY,
    "Fonderia Volskaya": Battleground.VOLSKAYA_FOUNDRY,
    "볼스카야 공장": Battleground.VOLSKAYA_FOUNDRY,
    "Odlewnia Volskaya Industries": Battleground.VOLSKAYA_FOUNDRY,
    "Fundição Volskaya": Battleground.VOLSKAYA_FOUNDRY,
    "Завод Вольской": Battleground.VOLSKAYA_FOUNDRY,
    "沃斯卡娅铸造厂": Battleground.VOLSKAYA_FOUNDRY,
    "伏斯凱亞鑄造廠": Battleground.VOLSKAYA_FOUNDRY,
    "Sprengkopfmanufaktur": Battleground.WARHEAD_JUNCTION,
    "Warhead Junction": Battleground.WARHEAD_JUNCTION,
    "Estación Nuclear": Battleground.WARHEAD_JUNCTION,
    "Cruce nuclear": Battleground.WARHEAD_JUNCTION,
    "Menace nucléaire": Battleground.WARHEAD_JUNCTION,
    "Stazione Atomica": Battleground.WARHEAD_JUNCTION,
    "핵탄두 격전지": Battleground.WARHEAD_JUNCTION,
    "Poligon Nuklearny": Battleground.WARHEAD_JUNCTION,
    "Junção da Ogiva": Battleground.WARHEAD_JUNCTION,
    "Ядерный полигон": Battleground.WARHEAD_JUNCTION,
    "弹头枢纽站": Battleground.WARHEAD_JUNCTION,
    "核武戰地": Battleground.WARHEAD_JUNCTION,
}


def import_heroprotocol(base_build):
    try:
        protocol = __import__(
            "heroprotocol.versions", fromlist=[f"protocol{base_build}"]
        )
        protocol = getattr(protocol, f"protocol{base_build}")
    except (ImportError, AttributeError):

        # unsupported base build, use previous build
        all_versions = [
            module_name
            for _, module_name, _ in pkgutil.iter_modules(
                heroprotocol.versions.__path__
            )
        ]
        fallback_build = int(all_versions[-1][-5:])

        try:
            protocol = __import__(
                "heroprotocol.versions", fromlist=[f"protocol{fallback_build}"]
            )
            protocol = getattr(protocol, f"protocol{fallback_build}")
        except (ImportError, AttributeError):
            return None

    return protocol


def get_gamemode(gamemode_id: int):
    try:
        gamemode = _GAMEMODE_DICT[gamemode_id]
    except KeyError:
        gamemode = Gamemode.OTHER
    return gamemode


def get_seconds(loops):
    return (loops - 610) / 16


def get_date(time_utc):
    return datetime.fromtimestamp((time_utc // 10000 - 11644473600000) / 1000)


def get_hero_from_internal(internal_name):
    return _INTERNAL_HERO_DICT[internal_name]


def get_hero_from_short(short_name):
    return _SHORT_HERO_DICT[short_name]


def get_hero_from_localized(localized_name):
    return _LOCALIZED_HERO_DICT[localized_name]


def get_battleground_from_internal(internal_name):
    return _INTERNAL_BATTLEGROUND_DICT[internal_name]


def get_battleground_from_localized(localized_name):
    return _LOCALIZED_BATTLEGROUND_DICT[localized_name]


def get_battletag(lobby_data, player_name):
    tag = ""
    to_search = b"%s#(\\d{4,8})" % player_name
    r = re.compile(to_search)
    s = r.search(lobby_data)
    if s:
        tag = s.groups(0)[0].decode("utf-8")
        player_name = player_name.decode("utf-8")
        return f"{player_name}#{tag}"
